/*
    module.js is part of Appudo

    Copyright (C) 2012-2016
        47d28b96748b359224fab1e766147be097c4fabb12633387c0d1968c0209abd4 source@appudo.com

    Licensed under the Apache License, Version 2.0

    See http://www.apache.org/licenses/LICENSE-2.0 for more information
*/

define({ root:
//begin v1.x content
({
	nview:'New View',
	nmark:'Register Marker',
	nsub:'Register Subpart',
	nmeta:'New Meta',
	ntbl:'New Table',
	nrow:'New Row',
	nsett:'New Setting',
	nrole:'New Role',
	nvar:'New Variable',
	nskin:'New Skin',
	chTmpl:'Choose Template',
	settings:'Settings',
	view:'View',
	views:'Views',
	data:'Data',
	code:'Code',
	prev:'Preview',
	mark:'Marker',
	sub:'Subpart',
	files:'Linked Files',
	tags:'Meta Tags',
	skin:'Skins',
	tbl:'Tables',
	rows:'Rows',
	sett:'Custom Settings',
	inst:'Installer',
	roles:'User Roles',
	vars:'Server Variables',
	msub:'Marker/Sub.',
	tab:'Table',
	full:'Fullscreen',
	refr:'Refresh',
	type:'Type',
	page:'Page',
	mod:'Module',
	ln:'Line',
	batch:'Cron Job',
	remote:'RPC Handler',
	socket:'WebSocket Listener',
	m2m:'M2M Handler',
	fldr:'Folder',
	title:'Title',
	file:'File',
	sid:'SkinId',
	def:'Default Value',
	group:'Group',
	dragf:'Drag a File from the File Tree into the Grid',
	amark:'New Marker',
	asub:'New Subpart',
	ameta:'New Meta with Data',
	afile:'New Linked File with Data',
	err:'Problems',
	cons:'Log',
	loc:'Location',
	inh:'Inherit',
	html:'HTML-Tag Data',
	doc:'Doctype-Tag Data',
	inhp:'Inherit from Parent',
	excl:'Exclude from Menu',
	rep:'Repeat',
	xhtml:'(X)HTML',
	cont:'Page Content',
	plain:'Plain Text',
	fold:'Base Folder',
	folders:'Folders',
	base:'Base',
	ext:'Extended',
	sec:'Secure (SSL)',
	ckp:'Cookie Path',
	week:'weekly',
	month:'monthly',
	acode:'Add Code',
	nmscode:'Insert funktion for Marker or Subpart',
	ahtml:'Insert Marker or Subpart Data',
	root:'Base Folder Marker',
	target:'Post Target Marker',
	npvar:'New POST Variable',
	ngvar:'New GET Variable',
	ncvar:'New Cookie Variable',
	nsvar:'New Session Variable',
	ncont:'No entry Point defined',
	ndata:'Select a Table to work with',
	idata:'Insert Data',
	query:'SQL Query',
	selView:'Select a View to edit',
    selErr:'Open item failed',
	dropF:'Drop a Folder from File Tree',
	mview:'Module View',
	nm:'#',
    msg:'Message',
    ws_disp:'Dispatch incomplete',
    ws_comp:'Compression',
    ws_bin:'Allow Binary',
    ws_txt:'Allow Text',
    ws_bsize:'Buffer Chunk (B)',
    ws_msize:'Message Limit (B)',
    ws_blimit:'Buffer Limit (B)',
    ws_climit:'Client Limit (num)',
    ws_tlimit:'Timeout (sec)',
    int_range:'Not an Integer or out of range.',
 })
//end v1.x content
,
'en':true,
'de':true
});
